import {Inter} from 'next/font/google'
import {BodySection} from "@/style/main.styled";
import {Navigation} from "@/components/Navbar/Navbar";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
const navLinks = [
    {
        name: 'Home',
        href: '/'
    },

    {
        name: 'About',
        href: '/information'
    }
]

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <BodySection suppressHydrationWarning={true}>
            <Navigation navLinks={navLinks}/>
            {children}
        </BodySection>
        </html>
    )
}
