import {BodySection} from "@/style/main.styled";
import {Navigation} from "@/components/Navbar/Navbar";
import {dir} from 'i18next'
import {NextIntlClientProvider} from 'next-intl';
import {notFound} from "next/navigation";


// const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
const navLinks = [
    {
        name: 'Home',
        href: '/'
    },

    {
        name: 'About',
        href: '/information'
    }
]

export default async function RootLayout({children, params}: {
    children: React.ReactNode,
    params: {
        page: string,
        slug: string,
        locale: string,
        locales: string[],
        defaultLocale: string,
        title: string,
        description: string,
        lang: string,
    }
}) {

    let messages;
    try {
        messages = (await import(`../../lang/${params.lang}.json`)).default;
    } catch (error) {
        notFound();
    }
    return (
        <html lang={params.lang} dir={dir(params.lang)}>
        <BodySection suppressHydrationWarning={true}>
            <NextIntlClientProvider locale={params.lang} messages={messages}>
                <Navigation navLinks={navLinks} lang={params.lang}/>
                {children}
            </NextIntlClientProvider>
        </BodySection>
        </html>
    )
}
